name: 'Tear Down Infra'

on:
  workflow_dispatch:
    branches: [ "main" ]

env:
  ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: 'Destroy Infra'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="aws_region=us-east-2" -var="aws_access_key=${{ env.ACCESS_KEY_ID }}" -var="aws_secret_access_key=${{ env.SECRET_ACCESS_KEY }}"
